//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bqxxb
    {
        public int fid { get; set; }
        public int ywbh { get; set; }
        public double gqzl { get; set; }
        public double bzm { get; set; }
        public double bcbqzl { get; set; }
        public double ybql { get; set; }
        public int bqwc { get; set; }
        public Nullable<int> wxdbh { get; set; }
    }
}
