//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class czry
    {
        public int Id { get; set; }
        public string bh { get; set; }
        public string xm { get; set; }
        public string dm { get; set; }
        public Nullable<int> opId { get; set; }
        public int zcyy { get; set; }
        public Nullable<int> FAgencyCode { get; set; }
    }
}
