//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class djgl
    {
        public int yhlx { get; set; }
        public decimal qj { get; set; }
        public string ms { get; set; }
        public int ckxl { get; set; }
        public int yxl { get; set; }
        public int bx { get; set; }
        public Nullable<byte> gs { get; set; }
        public int ID { get; set; }
    }
}
