//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hbjl
    {
        public int ywbh { get; set; }
        public string bzm { get; set; }
        public System.DateTime rq { get; set; }
        public string czy { get; set; }
        public Nullable<int> wxdbh { get; set; }
        public Nullable<double> dqqm { get; set; }
        public string dqbh { get; set; }
        public Nullable<int> cxbz { get; set; }
        public int ID { get; set; }
    }
}
