//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICModelContainer : DbContext
    {
        public ICModelContainer()
            : base("name=ICModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bqxxb> BqxxbSet { get; set; }
        public virtual DbSet<bhIndex> bhIndexSet { get; set; }
        public virtual DbSet<bqjzh> bqjzhSet { get; set; }
        public virtual DbSet<czry> czrySet { get; set; }
        public virtual DbSet<djgl> djglSet { get; set; }
        public virtual DbSet<hbjl> hbjlSet { get; set; }
        public virtual DbSet<hmd> hmdSet { get; set; }
        public virtual DbSet<hmdjs> hmdjsSet { get; set; }
        public virtual DbSet<jdlx> jdlxSet { get; set; }
        public virtual DbSet<wxdj> wxdjSet { get; set; }
        public virtual DbSet<ycxxb> ycxxbSet { get; set; }
        public virtual DbSet<yhxx> yhxxSet { get; set; }
        public virtual DbSet<yygl> yyglSet { get; set; }
        public virtual DbSet<yysj> yysjSet { get; set; }
        public virtual DbSet<zxgl> zxglSet { get; set; }
        public virtual DbSet<czjlb> czjlbSet { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
