//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wxdj
    {
        public int wxdbh { get; set; }
        public int ywbh { get; set; }
        public string yh { get; set; }
        public string zz { get; set; }
        public string tel { get; set; }
        public System.DateTime xlsj { get; set; }
        public int gzdm { get; set; }
        public byte hb { get; set; }
        public Nullable<double> bzm { get; set; }
        public string BefBh { get; set; }
        public string NowBh { get; set; }
        public Nullable<int> wxyy { get; set; }
        public Nullable<int> wxcs { get; set; }
        public Nullable<double> syql { get; set; }
        public string bz { get; set; }
        public string czy { get; set; }
    }
}
