//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ycxxb
    {
        public Nullable<int> ywbh { get; set; }
        public string hm { get; set; }
        public string zz { get; set; }
        public string tel { get; set; }
        public Nullable<int> gqzl { get; set; }
        public Nullable<int> zhgql { get; set; }
        public Nullable<System.DateTime> gqrq { get; set; }
        public Nullable<int> sfyc { get; set; }
        public Nullable<System.DateTime> rq { get; set; }
        public int ID { get; set; }
    }
}
