//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yhxx
    {
        public int ywbh { get; set; }
        public string hm { get; set; }
        public string zz { get; set; }
        public string tel { get; set; }
        public string bz { get; set; }
        public Nullable<System.DateTime> jdrq { get; set; }
        public Nullable<int> gqcs { get; set; }
        public Nullable<double> gqzl { get; set; }
        public string jdczy { get; set; }
        public Nullable<System.DateTime> gqrq { get; set; }
        public Nullable<double> xbzm { get; set; }
        public string yhmm { get; set; }
        public Nullable<double> bqzl { get; set; }
        public Nullable<int> bqcs { get; set; }
        public Nullable<int> yhlx { get; set; }
        public Nullable<int> sdbj { get; set; }
        public Nullable<System.DateTime> fkrq { get; set; }
        public string gqd { get; set; }
        public int kpbh { get; set; }
        public string zxh { get; set; }
        public Nullable<int> jdlx { get; set; }
        public Nullable<int> yhkx { get; set; }
        public Nullable<int> qtlx { get; set; }
    }
}
