//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICCardSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yysj
    {
        public int fid { get; set; }
        public int ywbh { get; set; }
        public int skcs { get; set; }
        public System.DateTime skrq { get; set; }
        public decimal skje { get; set; }
        public double skql { get; set; }
        public string czy { get; set; }
        public int bb { get; set; }
        public int hh { get; set; }
        public int sjkb { get; set; }
        public System.DateTime time { get; set; }
        public int gzzbh { get; set; }
        public int lstbz { get; set; }
        public int bqbz { get; set; }
        public int zfbz { get; set; }
        public string fpbh { get; set; }
    }
}
